import { Injectable, inject } from '@angular/core';
import { TickerStore } from '../state/ticker.store';
import { IndicatorSettings, IndicatorResults } from '../models/indicator.model';
import { DetectedPattern } from '../models/pattern.model';

/**
 * Generates Pine Script v5 code from the current chart state.
 * The generated script includes all active indicators and pattern annotations
 * as comments, ready to paste into TradingView's Pine Editor.
 */
@Injectable({ providedIn: 'root' })
export class PineScriptService {
  private readonly store = inject(TickerStore);

  /**
   * Generate a complete Pine Script v5 indicator script.
   * Uses the current ticker, timeframe, active indicators, and detected patterns.
   */
  generate(): string {
    const ticker = this.store.selectedTicker() ?? 'SPY';
    const timeframe = this.store.timeframe();
    const indicators = this.store.activeIndicators();
    const results = this.store.indicators();
    const patterns = this.store.patterns();

    const lines: string[] = [];

    // ─── Header ───────────────────────────────────────────────────
    lines.push('//@version=5');
    lines.push(`// Generated by Candle AI — ${ticker} (${timeframe})`);
    lines.push(`// Date: ${new Date().toISOString().split('T')[0]}`);
    lines.push('');
    lines.push(`indicator("Candle AI — ${ticker}", overlay=true, max_labels_count=500)`);
    lines.push('');

    // ─── Pattern Annotations (as comments + labels) ──────────────────
    if (patterns.length > 0) {
      lines.push('// ─── Detected Patterns ───────────────────────────────────────');
      for (const p of patterns) {
        const date = new Date(p.time * 1000).toISOString().split('T')[0];
        const sentiment = p.sentiment.toUpperCase();
        const type = formatPatternType(p.type);
        lines.push(`// [${date}] ${type} — ${sentiment} (confidence: ${(p.confidence * 100).toFixed(0)}%)`);
      }
      lines.push('');
    }

    // ─── SMA ──────────────────────────────────────────────────────
    if (indicators.sma20 || indicators.sma50 || indicators.sma200) {
      lines.push('// ─── Simple Moving Averages ───────────────────────────────────');
    }
    if (indicators.sma20 && results?.sma20) {
      lines.push(`sma20 = ta.sma(close, 20)`);
      lines.push(`plot(sma20, "SMA 20", color=color.blue, linewidth=1)`);
    }
    if (indicators.sma50 && results?.sma50) {
      lines.push(`sma50 = ta.sma(close, 50)`);
      lines.push(`plot(sma50, "SMA 50", color=color.orange, linewidth=1)`);
    }
    if (indicators.sma200 && results?.sma200) {
      lines.push(`sma200 = ta.sma(close, 200)`);
      lines.push(`plot(sma200, "SMA 200", color=color.red, linewidth=2)`);
    }
    if (indicators.sma20 || indicators.sma50 || indicators.sma200) {
      lines.push('');
    }

    // ─── EMA ──────────────────────────────────────────────────────
    if (indicators.ema9 || indicators.ema21) {
      lines.push('// ─── Exponential Moving Averages ──────────────────────────────');
    }
    if (indicators.ema9 && results?.ema9) {
      lines.push(`ema9 = ta.ema(close, 9)`);
      lines.push(`plot(ema9, "EMA 9", color=color.teal, linewidth=1)`);
    }
    if (indicators.ema21 && results?.ema21) {
      lines.push(`ema21 = ta.ema(close, 21)`);
      lines.push(`plot(ema21, "EMA 21", color=color.purple, linewidth=1)`);
    }
    if (indicators.ema9 || indicators.ema21) {
      lines.push('');
    }

    // ─── Bollinger Bands ──────────────────────────────────────────
    if (indicators.bb && results?.bb) {
      lines.push('// ─── Bollinger Bands ──────────────────────────────────────────');
      lines.push(`[bbMiddle, bbUpper, bbLower] = ta.bb(close, 20, 2)`);
      lines.push(`plot(bbMiddle, "BB Middle", color=color.gray, linewidth=1)`);
      lines.push(`bbUpperPlot = plot(bbUpper, "BB Upper", color=color.gray, linewidth=1, linestyle=plot.style_dashed)`);
      lines.push(`bbLowerPlot = plot(bbLower, "BB Lower", color=color.gray, linewidth=1, linestyle=plot.style_dashed)`);
      lines.push(`fill(bbUpperPlot, bbLowerPlot, color=color.new(color.gray, 90), title="BB Fill")`);
      lines.push('');
    }

    // ─── MACD ─────────────────────────────────────────────────────
    if (indicators.macd && results?.macd) {
      lines.push('// ─── MACD ─────────────────────────────────────────────────────');
      lines.push(`[macdLine, signalLine, histLine] = ta.macd(close, 12, 26, 9)`);
      lines.push(`plot(macdLine, "MACD", color=color.blue, linewidth=1, display=display.none)`);
      lines.push(`plot(signalLine, "Signal", color=color.orange, linewidth=1, display=display.none)`);
      lines.push(`plot(histLine, "Histogram", color=color.gray, style=plot.style_columns, display=display.none)`);
      lines.push('');
      lines.push('// To show MACD in a separate pane, change overlay=true to overlay=false');
      lines.push('// and uncomment the display params above.');
      lines.push('');
    }

    // ─── RSI ──────────────────────────────────────────────────────
    if (indicators.rsi && results?.rsi) {
      lines.push('// ─── RSI ──────────────────────────────────────────────────────');
      lines.push(`rsi14 = ta.rsi(close, 14)`);
      lines.push(`hline(70, "Overbought", color=color.red, linestyle=hline.style_dashed)`);
      lines.push(`hline(30, "Oversold", color=color.green, linestyle=hline.style_dashed)`);
      lines.push(`plot(rsi14, "RSI 14", color=color.purple, linewidth=1, display=display.none)`);
      lines.push('');
      lines.push('// To show RSI in a separate pane, change overlay=true to overlay=false');
      lines.push('// and uncomment the display params above.');
      lines.push('');
    }

    // ─── Volume Profile ───────────────────────────────────────────
    if (indicators.volumeProfile && results?.volumeProfile) {
      lines.push('// ─── Volume Profile ──────────────────────────────────────────');
      lines.push(`// POC (Point of Control): ${results.volumeProfile.poc.toFixed(2)}`);
      lines.push(`// Value Area High: ${results.volumeProfile.valueAreaHigh.toFixed(2)}`);
      lines.push(`// Value Area Low: ${results.volumeProfile.valueAreaLow.toFixed(2)}`);
      lines.push('// Note: Full volume profile requires manual implementation in Pine Script.');
      lines.push('// Use TradingView\'s built-in Volume Profile indicator for this.');
      lines.push('');
    }

    // ─── Pattern markers ──────────────────────────────────────────
    if (patterns.length > 0) {
      lines.push('// ─── Pattern Markers ─────────────────────────────────────────');
      lines.push('// Uncomment to show pattern labels on the chart:');
      for (const p of patterns) {
        const dateStr = formatPineDate(new Date(p.time * 1000));
        const label = formatPatternType(p.type);
        const color = p.sentiment === 'bullish' ? 'color.green' : p.sentiment === 'bearish' ? 'color.red' : 'color.yellow';
        lines.push(`// label.new(x=timestamp("${dateStr}"), y=high, text="${label}", color=${color}, style=label.style_label_down, yloc=yloc.abovebar)`);
      }
      lines.push('');
    }

    // ─── Footer ───────────────────────────────────────────────────
    lines.push('// ─── Instructions ────────────────────────────────────────────');
    lines.push('// 1. Open TradingView → Pine Editor');
    lines.push('// 2. Paste this script');
    lines.push('// 3. Click "Add to chart"');
    lines.push('// 4. Adjust settings as needed');
    lines.push('//');
    lines.push('// Tip: To show oscillators (RSI, MACD) in a separate pane,');
    lines.push('//      copy them into a new indicator with overlay=false.');
    lines.push('//      Remove "display=display.none" to make them visible.');

    return lines.join('\n');
  }

  /**
   * Generate a TradingView deep link for the current ticker.
   */
  getTradingViewUrl(): string {
    const ticker = this.store.selectedTicker() ?? 'SPY';
    // Map common symbols to TradingView format
    const symbol = mapToTradingViewSymbol(ticker);
    return `https://www.tradingview.com/chart/?symbol=${encodeURIComponent(symbol)}`;
  }
}

// ─── Helpers ──────────────────────────────────────────────────────

function formatPatternType(type: string): string {
  const map: Record<string, string> = {
    doji: 'Doji',
    hammer: 'Hammer',
    shooting_star: 'Shooting Star',
    bullish_engulfing: 'Bullish Engulfing',
    bearish_engulfing: 'Bearish Engulfing',
    morning_star: 'Morning Star',
    evening_star: 'Evening Star',
    bullish_harami: 'Bullish Harami',
    bearish_harami: 'Bearish Harami',
    three_white_soldiers: 'Three White Soldiers',
    three_black_crows: 'Three Black Crows',
  };
  return map[type] ?? type;
}

function formatPineDate(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  const h = String(date.getUTCHours()).padStart(2, '0');
  const min = String(date.getUTCMinutes()).padStart(2, '0');
  return `${y}-${m}-${d}T${h}:${min}`;
}

function mapToTradingViewSymbol(ticker: string): string {
  // TradingView uses specific exchange prefixes
  const map: Record<string, string> = {
    'BTC-USD': 'BINANCE:BTCUSD',
    'ETH-USD': 'BINANCE:ETHUSD',
    'GC=F': 'COMEX:GC1!',
    'SI=F': 'COMEX:SI1!',
    'CL=F': 'NYMEX:CL1!',
    'ES=F': 'CME_MINI:ES1!',
    'NQ=F': 'CME_MINI:NQ1!',
  };
  if (map[ticker]) return map[ticker];

  // US stocks: NASDAQ or NYSE
  return ticker.replace('=F', '').replace('-USD', '');
}
